site_name: bdep-oss-gui
site_url: https://byron.github.io/bdep-oss-gui
site_description: Open-Source Depedencies - for graphical user interfaces

repo_url: https://github.com/Byron/bdep-oss-oss
dev_addr: 127.0.0.1:9993

docs_dir: ../../src/md
site_dir: ../../doc/mkdocs/html

pages:
- ['index.md', 'Home']
- ['license.md', 'About', 'License']

theme: yeti

copyright: Copyright &copy; 2014, <a href="https://www.linkedin.com/in/sebastianthiel">Sebastian Thiel & Contributors</a>.
